### ISSUE TITLE
Build issue related to MultiThreaderBase.h

### ISSUE THREAD

**Issue by tashrifbillah** [BRAINSia/BRAINSTools#422]
```
In file included from /home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/include/itkTBBMultiThreader.h:22:0,
                 from /home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/src/itkTBBMultiThreader.cxx:19:
/home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/include/itkMultiThreaderBase.h: In lambda function:
/home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/include/itkMultiThreaderBase.h:358:15: error: ‘static void itk::MultiThreaderBase::HandleFilterProgress(itk::ProcessObject*, float)’ is protected
   static void HandleFilterProgress(ProcessObject *filter, float progress = -1.0f);
               ^
/home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/src/itkTBBMultiThreader.cxx:109:55: error: within this context
         MultiThreaderBase::HandleFilterProgress(filter);
                                                       ^
In file included from /home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/include/itkTBBMultiThreader.h:22:0,
                 from /home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/src/itkTBBMultiThreader.cxx:19:
/home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/include/itkMultiThreaderBase.h: In lambda function:
/home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/include/itkMultiThreaderBase.h:358:15: error: ‘static void itk::MultiThreaderBase::HandleFilterProgress(itk::ProcessObject*, float)’ is protected
   static void HandleFilterProgress(ProcessObject *filter, float progress = -1.0f);
               ^
/home/tb571/Documents/BRAINSTools/build/ITKv5/Modules/Core/Common/src/itkTBBMultiThreader.cxx:233:53: error: within this context
       MultiThreaderBase::HandleFilterProgress(filter);
                                                     ^
make[5]: *** [Modules/Core/Common/src/CMakeFiles/ITKCommon.dir/itkTBBMultiThreader.cxx.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [Modules/Core/Common/src/CMakeFiles/ITKCommon.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ITKv5-prefix/src/ITKv5-stamp/ITKv5-build] Error 2
make[1]: *** [CMakeFiles/ITKv5.dir/all] Error 2
make: *** [all] Error 2
```

Is there a commit I should try that builds without any error? I am using Centos 7 linux, 64 bit.

**Comment by hjmjohnson** [comment]
I'm working with the TBB development team to fix issues with TBB installs.  See #423

**Comment by tashrifbillah** [comment]
Has it been fixed?

**Comment by tashrifbillah** [comment]
I wish I tried it earlier. I didn't see a commit was added addressing my issue. However, it didn't work:

```
Performing C++ SOURCE FILE Test CXX_HAS_DISABLE_OPTIMIZATION_FLAG failed with the following output:
Change Dir: /home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_8a147/fast"
gmake[3]: Entering directory `/home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp'
/usr/bin/gmake -f CMakeFiles/cmTC_8a147.dir/build.make CMakeFiles/cmTC_8a147.dir/build
gmake[4]: Entering directory `/home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_8a147.dir/src.cxx.o
/usr/bin/c++    -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel  -Wno-array-bounds -fPIC      -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel -DCXX_HAS_DISABLE_OPTIMIZATION_FLAG   -std=c++11 -o CMakeFiles/cmTC_8a147.dir/src.cxx.o -c /home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp/src.cxx
/home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp/src.cxx:1:1: error: expected unqualified-id before ‘-’ token
 -O0
 ^
gmake[4]: *** [CMakeFiles/cmTC_8a147.dir/src.cxx.o] Error 1
gmake[4]: Leaving directory `/home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp'
gmake[3]: *** [cmTC_8a147/fast] Error 2
gmake[3]: Leaving directory `/home/tb571/BRAINSTools/build/BRAINSTools-build/CMakeFiles/CMakeTmp'

Source file was:
-O0
```

**Comment by tashrifbillah** [comment]
ping .. @hjmjohnson

**Comment by hjmjohnson** [comment]
@tashrifbillah I can not replicate your issue.  It looks like a compiler configuration problem.  What OS, compiler, environment are you using?

**Comment by tashrifbillah** [comment]
Centos 7
`cmake version 3.11.4`

```
gmake --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
Copyright (C) 2010  Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Comment by tashrifbillah** [comment]
By the way, I am using the default configuration.

**Comment by tashrifbillah** [comment]
Hi @hjmjohnson , where do we stand in diagnosing/solving this issue? Did we find out what is causing
`error: expected unqualified-id before ‘-’ token` ?

**Comment by tashrifbillah** [comment]
@hjmjohnson , I may have found the solution for my issue. Which version of cmake are you using? Previously, I was using 3.11.4 and that was yielding the above error.

However, when I updated to 3.14.2 (the latest), the error seems to disappear. Does it sound reasonable?

In brief, I am building against master branch on a Centos7 machine.

**Comment by hjmjohnson** [comment]
Perhaps.   I don’t do exhaustive testing on all Cmake versions.
